#!/bin/sh

source submit_job_multiple.sh sis1_pos1_gamma3009
source submit_job_multiple.sh sis1_pos2_gamma3009
source submit_job_multiple.sh sis1_pos3_gamma3009
source submit_job_multiple.sh sis1_pos4_gamma3009
source submit_job_multiple.sh sis2_pos1_gamma3009
source submit_job_multiple.sh sis2_pos2_gamma3009
source submit_job_multiple.sh sis2_pos3_gamma3009
source submit_job_multiple.sh sis2_pos4_gamma3009
source submit_job_multiple.sh sis3_pos1_gamma3009
source submit_job_multiple.sh sis3_pos2_gamma3009
source submit_job_multiple.sh sis3_pos3_gamma3009
source submit_job_multiple.sh sis3_pos4_gamma3009
source submit_job_multiple_fullCo.sh sis1_pos1_fullCo
source submit_job_multiple_fullCo.sh sis1_pos2_fullCo
source submit_job_multiple_fullCo.sh sis1_pos3_fullCo
source submit_job_multiple_fullCo.sh sis1_pos4_fullCo
source submit_job_multiple_fullCo.sh sis2_pos1_fullCo
source submit_job_multiple_fullCo.sh sis2_pos2_fullCo
source submit_job_multiple_fullCo.sh sis2_pos3_fullCo
source submit_job_multiple_fullCo.sh sis2_pos4_fullCo
source submit_job_multiple_fullCo.sh sis3_pos1_fullCo
source submit_job_multiple_fullCo.sh sis3_pos2_fullCo
source submit_job_multiple_fullCo.sh sis3_pos3_fullCo
source submit_job_multiple_fullCo.sh sis3_pos4_fullCo

